# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# **but __NOT__ in front matter!!**

remote_theme: "mmistakes/minimal-mistakes@4.14.1"
title: Ritika Mukherji
url: https://ritika-mukherji.github.io/
name: Ritika Mukherji
##  > # this means to ignore newlines until "baseurl:"
description: Ritika Mukherji personal site
baseurl: "/"
show_downloads: false

# twitter_username: edgriebel
# github_username: edgriebel
# linkedin_username: edgriebel

# Build settings
markdown: kramdown
highlighter: rouge

# unused-theme: jekyll-theme-time-machine ## bug in post title uses site title
# pretty plain! theme: jekyll-theme-slate
# Too Minimal!! theme: jekyll-theme-minimal
# unused-theme: jekyll-theme-minimal
# unused-theme: jekyll-theme-primer
# unused-theme: minima
# unused-theme: jekyll-theme-tactile
# unused-theme: jekyll-theme-cayman
# unused-theme: jekyll-theme-modernist
# unused-theme: jekyll-theme-leap-day
# unused-remote_theme: daattali/beautiful-jekyll # Unsupported as a remote_theme

#
# minimal-mistakes customizations
#
minimal_mistakes_skin: "neon" # air, contrast, dark, default, mint, neon, sunrise
title_separator: "|"
breadcrumbs: true
paginate: 10
paginate_path: /page:num/
# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       read_time: true
#       author_profile: true
#       share: true
#       related: true
author:
   name: "Ritika Mukherji"
   avatar: "https://media.licdn.com/dms/image/D4E03AQEdZ1flHraYJg/profile-displayphoto-shrink_200_200/0/1676237757879?e=2147483647&v=beta&t=G9cHPZR7oTw4cOUFeeWFTingP7sGqsDHuxAEycOY3rg"
   bio: "Oxford DPhil student"
   links:
     - label: "GitHub"
       icon:  "fab fa-fw fa-github"
       url:   ""
     - label: "My Resume"
       icon:  "fas fa-file-pdf"
       url:   ""
     - label: "LinkedIn"
       icon:  "fab fa-linkedin"
       url:   ""
repository: ritika-mukherji/ritika-mukherji.github.io
analytics:
   provider: 'google-gtag'
   google:
     tracking_id: 'UA-50378804-1'
     anonymize_ip: false
#
# END minimal-mistakes customizations
#

repository: ritika-mukherji/ritika-mukherji.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap # minimal-mistakes
  - jekyll-include-cache # minimal-mistakes
  - jekyll-paginate # minimal-mistakes
  - jekyll-gist # minimal-mistakes
  - jekyll-remote-theme

whitelist: 
  - jekyll-feed
  - jekyll-sitemap # minimal-mistakes
  - jekyll-include-cache # minimal-mistakes
  - jekyll-paginate # minimal-mistakes
  - jekyll-gist # minimal-mistakes
  - jekyll-remote-theme
  
include:
  # - _pages
# exclude:
  # - Gemfile
  # - Gemfile.lock
        
# minimal-mistakes customizations
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# END minimal-mistakes customizations

# Should this be :year-:title? /:year/:month/:title? /:year/:title? /:title?
permalink: /:categories/:year-:title/
